POST {{base_url_fp}}/user
Content-Type: application/json

{
  "firstName": "alisson",
  "lastName": "morais",
  "email": "alisson.morais@olhonocarro.com.br"
}

###

GET {{base_url_fp}}/user/1

###

POST {{base_url_fp}}/user/deposit
Content-Type: application/json

{
  "userId": 1,
  "amount": "50.49"
}

###

POST {{base_url_fp}}/user/withdraw
Content-Type: application/json

{
  "userId": 1,
  "amount": "12.8"
}

###

GET {{base_url_fp}}/user/balance/1

###

POST {{base_url_fp}}/transaction/transference
Content-Type: application/json

{
  "fromUserId": 1,
  "toUserId": 2,
  "amount": "3.91"
}

###